### ISSUE TITLE
Why fork?

### ISSUE THREAD

**Issue by buzz** [1024mb/imdb-link-em-all-fork#1]
Hey there!

Nice to see you enjoy Link 'em all.
Is there a reason why you chose to fork the project? I think the user base could profit from your improvements by contributing to the main codebase.

Thanks
b

**Comment by 1024mb** [comment]
Hey, I don't know how I missed the notification, I think I never got it, sorry for the late reply.  
I've forked the script mainly (well, only, you can say) because I changed some aesthetics parts of it ([See the last point](https://github.com/1024mb/imdb-link-em-all-fork#principal-only-changes-from-original-script)) which at the time I didn't think you would have liked, I'm saying this because you choose to have it one way originally and I didn't want to mess with your choices in that regard. Other than that there is no other reason really.
